# Site settings
title: Fardjad Davari
email: public@fardjad.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Fardjad Davari. 
  This is my personal website, where I post my writing and my works.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.fardjad.com" # the base hostname & protocol for your site
twitter_username: therealfardjad
github_username: fardjad
stackoverflow_username: 303270

# Build settings
markdown: kramdown
