# Site settings
title: Fardjad Davari
email: public@fardjad.com
description: My name is Fardjad Davari. This is my personal website!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.fardjad.com" # the base hostname & protocol for your site
twitter_username: dfardjad
github_username: fardjad
stackoverflow_username: 303270
linkedin_username: fardjad

# Build settings
markdown: kramdown
